# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  versioning:
    enabled: true
    default_version: 1
    resolvers:
      query:
        enabled: true
        parameter_name: version
      custom_header:
        enabled: true
        header_name: X-Accept-Version
      media_type:
        enabled: true
        regex: /(v|version)=(?P<version>[0-9\.]+)/
    guessing_order:
      - query
      - custom_header
      - media_type
  view: ~
  format_listener: ~